version: '3'
services:
  filter:
    build: ./packages-filter
    command: sh -c "go run ./main.go"
    volumes:
      - "packages-filter:/go/src/packages-filter"

  api:
    build: ./packages-api
    ports:
      - "8080:8080"
    volumes:
      - "packages-filter:/go/src/packages-filter"
      - "packages-api:/go/src/packages-api"
    depends_on:
      filter:
        condition: service_completed_successfully
    command: sh -c "cp -r /go/src/packages-filter/json /go/src/packages-api/ && go run ./main.go"

volumes:
  packages-filter:
  packages-api:
